repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
        exclude: ^\.vscode\/.*$
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
  - repo: https://github.com/hhatto/autopep8
    rev: 'v2.3.1'
    hooks:
    - id: autopep8
